# git:
#   allBranchesLogCmd: git log --graph --color=always --date=format:'%Y-%m-%d %H:%M:%S'
#   branchLogCmd: git log --graph --color=always --date=format:'%Y-%m-%d %H:%M:%S'
gui:
  nerdFontsVersion: "3"

